export const SET_FIRST_PLAYER = 'SET_FIRST_PLAYER'
export const SET_SECOND_PLAYER = 'SET_SECOND_PLAYER'

export const SET_FIRST_ICON = 'SET_FIRST_ICON'
export const SET_SECOND_ICON = 'SET_SECOND_ICON'
export const SET_THIRD_ICON = 'SET_THIRD_ICON'
export const SET_FOURTH_ICON = 'SET_FOURTH_ICON'
export const SET_FIFTH_ICON = 'SET_FIFTH_ICON'
export const SET_SIXTH_ICON = 'SET_SIXTH_ICON'

export const SHOW_FIRST_PAGE = 'SHOW_FIRST_PAGE'
export const HIDE_FIRST_PAGE = 'HIDE_FIRST_PAGE'
export const SHOW_SECOND_PAGE = 'SHOW_SECOND_PAGE'
export const HIDE_SECOND_PAGE = 'HIDE_SECOND_PAGE'
